### ISSUE TITLE
How about Image deletion?

### ISSUE THREAD

**Issue by larrystone** [IAMOTZ/node-react-cloudinary#1]
Nice work making this project available. I am thinking how about support for image deletion from backend?
Can this be done?

**Comment by IAMOTZ** [comment]
Hi, @larrystone.
For sure, it is possible to delete images in the cloud from the backend and there is a very good documentation on how to do that [here](https://cloudinary.com/documentation/node_image_upload#update_and_delete_images).
I wanted this project to restricted to just image upload to make it easy to study, but it is going to be nice to also implement deleting images from the cloud as a **bonus**. 
If you are able to implement the feature, please do raise a Pull Request.
